[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

# Redirect for Google Ads in case that someone enters the URL written in the ad
[[redirects]]
  from = "/entwicklung"
  to = "/individuelle-entwicklung/"

[[redirects]]
  from = "/#team"
  to = "/ueber-uns#team"

[[redirects]]
  from = "/#blog"
  to = "/blog/"

[[redirects]]
  from = "/#kontakt"
  to = "/kontakt/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
