
# Redirect for Google Ads in case that someone enters the URL written in the ad
[[redirects]]
from = "/entwicklung"
to = "/individuelle-entwicklung/"

[[redirects]]
from = "/#team"
to = "/ueber-uns#team"

[[redirects]]
from = "/#blog"
to = "/blog/"

[[redirects]]
from = "/vorgehensweise/"
to = "/vorgehen/"

[[redirects]]
from = "/#kontakt"
to = "/kontakt/"

[[redirects]]
from = "/gaston"
to = "/payflink/"

[[redirects]]
from = "/app-entwickeln-schweiz"
to = "/app-erstellen-schweiz/"
